"""Generate components/cinematic-site.css from the approved standalone stylesheet.

viper-net-site/assets/styles.css stays the source of truth for the design. This
rewrites it for the Next.js app mechanically, so the two never drift by hand:

  - every class gets the vn- prefix, and every id too, since names like .hero,
    .band and .step are generic enough to collide with anything else on the site
  - everything is scoped under .vn-root, including the bare element selectors,
    so nothing here reaches the admin pages or the rest of the app
  - :root, html and body collapse into .vn-root, which is the page wrapper
  - keyframe names are prefixed and their references rewritten with them
  - font files point at /fonts/ in public/ instead of a relative assets folder

Run: python3 review/port-css.py
"""
import pathlib, re

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "viper-net-site" / "assets" / "styles.css"
OUT = ROOT / "components" / "cinematic-site.css"

css = SRC.read_text()

# url(...) payloads are paths, not selectors: ".jpg" in a filename must never be
# treated as a class name. Mask them, prefix, then restore and repoint at public/
URLS = []
def _mask(m):
    URLS.append(m.group(0))
    return "__VN_URL_%d__" % (len(URLS) - 1)
css = re.sub(r"url\([^)]*\)", _mask, css)

CLASSES = sorted(set(re.findall(r"\.([a-zA-Z][a-zA-Z0-9_-]*)", css)), key=len, reverse=True)
IDS = sorted(set(re.findall(r"#([a-zA-Z][a-zA-Z0-9_-]*)", css)), key=len, reverse=True)
KEYFRAMES = sorted(set(re.findall(r"@keyframes\s+([a-zA-Z][\w-]*)", css)), key=len, reverse=True)

# hex colours contain no leading-# selector risk here, but #fff-style values do
# look like ids, so only rename ids that are actually declared as keyframes or
# selectors in this file
IDS = [i for i in IDS if not re.fullmatch(r"[0-9a-fA-F]{3,8}", i)]

for name in CLASSES:
    css = re.sub(r"\.%s\b" % re.escape(name), ".vn-%s" % name, css)
for name in IDS:
    css = re.sub(r"#%s\b" % re.escape(name), "#vn-%s" % name, css)
for name in KEYFRAMES:
    css = re.sub(r"@keyframes\s+%s\b" % re.escape(name), "@keyframes vn-%s" % name, css)
    # animation shorthand and animation-name both reference it
    css = re.sub(r"(animation(?:-name)?\s*:[^;}]*?)\b%s\b" % re.escape(name), r"\1vn-%s" % name, css)

for i, raw in enumerate(URLS):
    # the standalone build keeps these beside the stylesheet; Next serves them
    # from public/
    raw = (raw.replace("fonts/", "/fonts/")
              .replace('"hero-', '"/hero/hero-').replace("'hero-", "'/hero/hero-")
              .replace('"case-', '"/work/case-').replace("'case-", "'/work/case-"))
    css = css.replace("__VN_URL_%d__" % i, raw)

def scope_selector(sel):
    sel = sel.strip()
    if not sel or sel.startswith("@") or sel.startswith("from") or sel.startswith("to") or re.fullmatch(r"[\d.]+%", sel):
        return sel
    # the document-level selectors all become the page wrapper itself
    if sel in (":root", "html", "body", "html,body"):
        return ".vn-root"
    if sel.startswith("body."):
        return ".vn-root" + sel[4:]
    if sel.startswith(".vn-root"):
        return sel
    return ".vn-root " + sel

# walk the stylesheet and scope every selector list, leaving at-rule bodies to
# be walked as their own blocks
def transform(block):
    out = []
    i = 0
    while i < len(block):
        brace = block.find("{", i)
        if brace == -1:
            out.append(block[i:])
            break
        prelude = block[i:brace]
        # find the matching close brace
        depth, j = 1, brace + 1
        while j < len(block) and depth:
            if block[j] == "{":
                depth += 1
            elif block[j] == "}":
                depth -= 1
            j += 1
        body = block[brace + 1:j - 1]
        head = prelude.strip()
        comment = ""
        m = re.match(r"(\s*(?:/\*.*?\*/\s*)*)(.*)", prelude, re.S)
        if m:
            comment, head = m.group(1), m.group(2).strip()
        if head.startswith("@keyframes"):
            out.append(comment + head + "{" + body + "}")
        elif head.startswith("@media") or head.startswith("@supports"):
            out.append(comment + head + "{" + transform(body) + "}")
        elif head.startswith("@"):
            out.append(comment + head + "{" + body + "}")
        else:
            sels = ",".join(scope_selector(s) for s in head.split(","))
            out.append(comment + sels + "{" + body + "}")
        i = j
    return "".join(out)

FONTS = (ROOT / "viper-net-site" / "assets" / "fonts.css").read_text()
FONTS = FONTS.replace("url('fonts/", "url('/fonts/")

banner = ("/* GENERATED by review/port-css.py from viper-net-site/assets/styles.css.\n"
          "   Edit the source stylesheet and re-run the script; do not edit this file. */\n")
OUT.write_text(banner + FONTS + "\n" + transform(css))
print(f"{OUT}  {len(OUT.read_text().splitlines())} lines")
